# Generated by Django 6.0 on 2026-03-26 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='habitaciones',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portal.tipoinmueble'),
        ),
    ]
