# Generated by Django 6.0 on 2026-03-26 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_ciudad_inmueble_descripcion_inmueble_habitaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='portal.ciudad'),
        ),
    ]
